### ISSUE TITLE
HomeButton Disable

### ISSUE THREAD

**Issue by ffurkanhas** [nour-elghareeb/pincode-lock#1]
Firstly thanks for the project. But I have a question. Is there any way to disable home button?

**Comment by nour-elghareeb** [comment]
I'm sorry, what do you mean by the home button?

**Comment by ffurkanhas** [comment]
http://45.76.167.77/wp-content/uploads/2017/01/AndroidHomeButton.jpg this button

I mean if user click home button, the lock screen should not disappear it should work like stock lock screen user cannot finish lockscreen activity without entering correct password

**Comment by ffurkanhas** [comment]
I mean if user click home button, the lock screen should not disappear it should work like stock lock screen user cannot finish lockscreen activity without entering correct password

**Comment by nour-elghareeb** [comment]
Aha, I see.
I'm afraid what you're asking for is impossible. As far as I know, you cannot keep users from exiting your app (That's what the home button is for).. What you'd like to do is keep user from accessing specific activity/fragment when they are not authenticated.

This library is just a PIN input view. It does not handle any of the authentication/verification process. 
You can implement this part on your own. The logic here is pretty simple. All you need to do is ask the user for a PIN code and store it somehow on your device (encrypted of course) so you can authenticate the user in the future. 

Hope this clears the issue for you.

**Comment by ffurkanhas** [comment]
Thanks for your answer.
